plugins:
  conforma:
    policy-templates: ./policy-templates/opa
    policy-output: ./policies/opa
    policy-results: ./policy-results/opa
    bundle-location: oci::ghcr.io/{{ ORG }}/opa-bundle:dev
