name: "Run Checks"
description: "Run directory checks in the GitHub Repository"

runs:
  using: "composite"
  steps:
    - name: Setup snappy
      uses: carabiner-dev/actions/install/snappy@e1c6f772cc46a2dce1def4b8a1545249b3af757e

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Setup ORAS CLI
      uses: oras-project/setup-oras@8d34698a59f5ffe24821f0b48ab62a3de8b64b20 # v1.2.3

    - name: Retrieve data
      env:
        GITHUB_TOKEN: ${{ github.token }}
        ORG: ${{ github.event.repository.owner.login }}
        REPO: ${{ github.event.repository.name }}
      run: |
        snappy snap builtin:github/branch-rules.yaml -v ORG="$ORG" -v REPO="$REPO" -v BRANCH='main' > input.json
      shell: bash

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Install EC
      shell: bash
      run: |
        curl -sLO https://github.com/conforma/cli/releases/download/snapshot/ec_linux_amd64
        chmod +x ec_linux_amd64
        
    - name: Run EC Validate
      id: ec_validate
      continue-on-error: true
      shell: bash
      run: |
        ./ec_linux_amd64 validate input --policy "policy.yaml" --file input.json --output json=policy-results/opa/github_branch_protection.json
  
